//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("ConvertIfc2Json")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("7.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("7.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("ConvertIfc2Json")]
[assembly: System.Reflection.AssemblyTitleAttribute("ConvertIfc2Json")]
[assembly: System.Reflection.AssemblyVersionAttribute("7.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

